### ISSUE TITLE
tmux 2.9-1 issues

### ISSUE THREAD

**Issue by japrogramer** [edkolev/tmuxline.vim#102] opened 2019-04-26 21:48 UTC
This are the issues ..
```
/home/archangel/.tmuxline.conf:25: invalid or unknown command: set -g status-left "#[fg=colour18,bg=colour4,bold] #S #[fg=colour4,bg=colour19,nobold,nounderscore,noitalics]#[fg=colour7,bg=colour19] #I:#P > #W #[fg=colour19,bg=colour18,nobold,nounderscore,noitalics]#[fg=colour7,bg=colour18] #(whoami) > #(uptime | cut -d \" \" -f 2,3| sed -i \"s/[
/home/archangel/.tmuxline.conf:6: invalid option: status-attr
/home/archangel/.tmuxline.conf:7: invalid option: message-command-bg
/home/archangel/.tmuxline.conf:9: invalid option: pane-active-border-fg
/home/archangel/.tmuxline.conf:11: invalid option: message-command-fg
/home/archangel/.tmuxline.conf:12: invalid option: pane-border-fg
/home/archangel/.tmuxline.conf:13: invalid option: message-bg
/home/archangel/.tmuxline.conf:14: invalid option: status-left-attr
/home/archangel/.tmuxline.conf:15: invalid option: status-right-attr
/home/archangel/.tmuxline.conf:17: invalid option: message-fg
/home/archangel/.tmuxline.conf:18: invalid option: window-status-fg
/home/archangel/.tmuxline.conf:19: invalid option: window-status-attr
/home/archangel/.tmuxline.conf:20: invalid option: window-status-activity-bg
/home/archangel/.tmuxline.conf:21: invalid option: window-status-activity-attr
/home/archangel/.tmuxline.conf:22: invalid option: window-status-activity-fg
/home/archangel/.tmuxline.conf:24: invalid option: window-status-bg
```

here is  the file

```
# This tmux statusbar config was created by tmuxline.vim
# on Fri, 26 Apr 2019

set -g status-justify "centre"
set -g status "on"
set -g status-attr "none"
set -g message-command-bg "colour19"
set -g status-left-length "100"
set -g pane-active-border-fg "colour4"
set -g status-bg "colour18"
set -g message-command-fg "colour7"
set -g pane-border-fg "colour19"
set -g message-bg "colour19"
set -g status-left-attr "none"
set -g status-right-attr "none"
set -g status-right-length "100"
set -g message-fg "colour7"
setw -g window-status-fg "colour7"
setw -g window-status-attr "none"
setw -g window-status-activity-bg "colour18"
setw -g window-status-activity-attr "none"
setw -g window-status-activity-fg "colour4"
setw -g window-status-separator ""
setw -g window-status-bg "colour18"
set -g status-left "#[fg=colour18,bg=colour4,bold] #S #[fg=colour4,bg=colour19,nobold,nounderscore,noitalics]#[fg=colour7,bg=colour19] #I:#P > #W #[fg=colour19,bg=colour18,nobold,nounderscore,noitalics]#[fg=colour7,bg=colour18] #(whoami) > #(uptime | cut -d \" \" -f 2,3| sed -i \"s/[
```

**Comment by secuvim** [comment] 2019-04-28 15:27
This seems to be a duplicate of #100.

@japrogramer You can fix your generated file by replacing the relevant parts with the new style:
`set -g status-justify "centre"
set -g status "on"
set -g status-style "none"
set -g message-command-style bg="colour19"
set -g status-left-length "100"
set -g pane-active-border-style fg="colour4"
set -g status-style bg="colour18"
set -g message-command-style fg="colour7"
set -g pane-border-style fg="colour19"
set -g message-style bg="colour19"
set -g status-left-style "none"
set -g status-right-style "none"
set -g status-right-length "100"
set -g message-style fg="colour7"
setw -g window-status-style fg="colour7"
setw -g window-status-style "none"
setw -g window-status-activity-style bg="colour18"
setw -g window-status-activity-style "none"
setw -g window-status-activity-style fg="colour4"
setw -g window-status-separator ""
setw -g window-status-style bg="colour18"
set -g status-left "#[fg=colour18,bg=colour4,bold] #S #[fg=colour4,bg=colour19,nobold,nounderscore,noitalics]#[fg=colour7,bg=colour19] #I:#P > #W #[fg=colour19,bg=colour18,nobold,nounderscore,noitalics]#[fg=colour7,bg=colour18] #(whoami) > #(uptime | cut -d \" \" -f 2,3| sed -i \"s/[
`

**Comment by jgliner** [comment] 2019-04-29 16:47
Works perfectly, @secuvim! Thanks! For reference, this is what I had to change in order to get my .tmuxlinerc back to 100%:

**BEFORE**

```vim
set -g status-bg "colour249"
set -g message-command-fg "colour249"
set -g status-justify "left"
set -g status-left-length "100"
set -g status "on"
set -g pane-active-border-fg "colour249"
set -g message-bg "colour234"
set -g status-right-length "100"
set -g status-right-attr "none"
set -g message-fg "colour249"
set -g message-command-bg "colour234"
set -g status-attr "none"
set -g pane-border-fg "colour234"
set -g status-left-attr "none"
setw -g window-status-fg "colour234"
setw -g window-status-attr "none"
setw -g window-status-activity-bg "colour249"
setw -g window-status-activity-attr "none"
setw -g window-status-activity-fg "colour234"
setw -g window-status-separator ""
setw -g window-status-bg "colour249"
set -g status-left "#[fg=colour237,bg=colour249] #S #[fg=colour249,bg=colour249,nobold,nounderscore,noitalics]"
set -g status-right "#[fg=colour237,bg=colour249,bold]  #(tmux-spotify-info)  #[fg=colour234,bg=colour249,nobold,nounderscore,noitalics]#[fg=colour249,bg=colour234]  #(readWeather)    %a | %b %d %Y    #(date +\"%r\")    #(/Users/jarrettgliner/.bash-stuff.d/tmux-battery/tmux-battery)  #[fg=colour249,bg=colour234,nobold,nounderscore,noitalics]#[fg=colour234,bg=colour249] #h "
setw -g window-status-format "#[fg=colour234,bg=colour249] #I #[fg=colour234,bg=colour249] #W "
setw -g window-status-current-format "#[fg=colour249,bg=colour234,nobold,nounderscore,noitalics]#[fg=colour249,bg=colour234] #I #[fg=colour249,bg=colour234] #W #[fg=colour234,bg=colour249,nobold,nounderscore,noitalics]"

```

**AFTER**
```vim
set -g status-bg "colour249"
set -g message-command-style fg="colour249"
set -g status-justify "left"
set -g status-left-length "100"
set -g status "on"
set -g pane-active-border-style fg="colour249"
set -g message-style bg="colour234"
set -g status-right-length "100"
set -g status-right-style "none"
set -g message-style fg="colour249"
set -g message-command-style bg="colour234"
set -g status-left-style "none"
set -g status-right-style "none"
set -g pane-border-style fg="colour234"
set -g status-left-style "none"
setw -g window-status-style fg="colour234"
setw -g window-status-style "none"
setw -g window-status-activity-style bg="colour249"
setw -g window-status-activity-style "none"
setw -g window-status-activity-style fg="colour234"
setw -g window-status-separator ""
setw -g window-status-style bg="colour249"
set -g status-left "#[fg=colour237,bg=colour249] #S #[fg=colour249,bg=colour249,nobold,nounderscore,noitalics]"
set -g status-right "#[fg=colour237,bg=colour249,bold]  #(tmux-spotify-info)  #[fg=colour234,bg=colour249,nobold,nounderscore,noitalics]#[fg=colour249,bg=colour234]  #(readWeather)    %a | %b %d %Y    #(date +\"%r\")    #(/Users/jarrettgliner/.bash-stuff.d/tmux-battery/tmux-battery)  #[fg=colour249,bg=colour234,nobold,nounderscore,noitalics]#[fg=colour234,bg=colour249] #h "
setw -g window-status-format "#[fg=colour234,bg=colour249] #I #[fg=colour234,bg=colour249] #W "
setw -g window-status-current-format "#[fg=colour249,bg=colour234,nobold,nounderscore,noitalics]#[fg=colour249,bg=colour234] #I #[fg=colour249,bg=colour234] #W #[fg=colour234,bg=colour249,nobold,nounderscore,noitalics]"
```

**Comment by japrogramer** [comment] 2019-04-29 21:29
@secuvim when will the changes be in master?

**Closed** 2019-05-15 12:48 UTC
